/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#006d37',
        'primary-container': '#2ecc71',
        'on-primary': '#ffffff',
        'on-primary-container': '#005027',
        'primary-fixed': '#6bfe9c',
        'primary-fixed-dim': '#4ae183',
        'on-primary-fixed': '#00210c',
        'on-primary-fixed-variant': '#005228',
        'inverse-primary': '#4ae183',
        secondary: '#0051d3',
        'secondary-container': '#226afc',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b3c5ff',
        'on-secondary-fixed': '#00174a',
        'on-secondary-fixed-variant': '#003ea6',
        tertiary: '#98472a',
        'tertiary-container': '#ff9875',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#772e14',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-fixed': '#390c00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-tint': '#006d37',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#3d4a3e',
        outline: '#6c7b6d',
        'outline-variant': '#bbcbbb',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        background: '#f8f9fa',
        'on-background': '#191c1d',
      },
      fontFamily: {
        'jakarta': ['PlusJakartaSans_400Regular'],
        'jakarta-medium': ['PlusJakartaSans_500Medium'],
        'jakarta-semibold': ['PlusJakartaSans_600SemiBold'],
        'jakarta-bold': ['PlusJakartaSans_700Bold'],
        'jakarta-extrabold': ['PlusJakartaSans_800ExtraBold'],
      },
      borderRadius: {
        'card': 20,
        'input': 12,
        'button': 12,
        'chip': 9999,
      },
      spacing: {
        'xs': 4,
        'sm': 8,
        'md': 16,
        'lg': 24,
        'xl': 32,
        'container': 20,
        'gutter': 12,
      },
    },
  },
  plugins: [],
};
