/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#FF6B1A',
        'primary-container': '#FFD7BF',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#5A1F00',
        'primary-fixed': '#FFD7BF',
        'primary-fixed-dim': '#FFB088',
        'on-primary-fixed': '#2B0E00',
        'on-primary-fixed-variant': '#5A1F00',
        'inverse-primary': '#FFB088',
        secondary: '#F5C518',
        'secondary-container': '#FFEEB0',
        'on-secondary': '#1A1300',
        'on-secondary-container': '#3A2A00',
        'secondary-fixed': '#FFEEB0',
        'secondary-fixed-dim': '#FFE07A',
        'on-secondary-fixed': '#1A1300',
        'on-secondary-fixed-variant': '#3A2A00',
        tertiary: '#8B4A1F',
        'tertiary-container': '#FFD7BF',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#5A1F00',
        'tertiary-fixed': '#FFD7BF',
        'tertiary-fixed-dim': '#FFB088',
        'on-tertiary-fixed': '#2B0E00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#F8F4EB',
        'surface-bright': '#FBF8F1',
        'surface-dim': '#E8E1D0',
        'surface-container': '#F2EDE0',
        'surface-container-low': '#FAF6EE',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-high': '#EBE5D4',
        'surface-container-highest': '#E4DCC8',
        'surface-tint': '#FF6B1A',
        'surface-variant': '#EBE5D4',
        'on-surface': '#0F0F0F',
        'on-surface-variant': '#3A3A3A',
        outline: '#7A7368',
        'outline-variant': '#D9D2C3',
        'inverse-surface': '#2A2622',
        'inverse-on-surface': '#F8F4EB',
        background: '#F8F4EB',
        'on-background': '#0F0F0F',
      },
      fontFamily: {
        'jakarta': ['PlusJakartaSans_400Regular'],
        'jakarta-medium': ['PlusJakartaSans_500Medium'],
        'jakarta-semibold': ['PlusJakartaSans_600SemiBold'],
        'jakarta-bold': ['PlusJakartaSans_700Bold'],
        'jakarta-extrabold': ['PlusJakartaSans_800ExtraBold'],
      },
      borderRadius: {
        'card': 20,
        'input': 12,
        'button': 12,
        'chip': 9999,
      },
      spacing: {
        'xs': 4,
        'sm': 8,
        'md': 16,
        'lg': 24,
        'xl': 32,
        'container': 20,
        'gutter': 12,
      },
    },
  },
  plugins: [],
};
