export const NICARAGUAN_CITIES = [
  'Managua',
  'León',
  'Granada',
  'Masaya',
  'Chinandega',
  'Matagalpa',
  'Estelí',
  'Jinotega',
  'Rivas',
  'Bluefields',
  'Juigalpa',
  'Ocotal',
  'Somoto',
  'Diriamba',
  'Jinotepe',
  'San Juan del Sur',
  'Ciudad Sandino',
  'Tipitapa',
  'UCA Managua',
  'UNAN Managua',
] as const;

export const POPULAR_ROUTES = [
  { origin: 'Managua', destination: 'Masaya' },
  { origin: 'Managua', destination: 'Granada' },
  { origin: 'Managua', destination: 'León' },
  { origin: 'León', destination: 'Managua' },
  { origin: 'Granada', destination: 'Managua' },
  { origin: 'Masaya', destination: 'Managua' },
  { origin: 'Chinandega', destination: 'León' },
  { origin: 'Estelí', destination: 'Managua' },
  { origin: 'Ciudad Sandino', destination: 'UCA Managua' },
  { origin: 'Matagalpa', destination: 'Managua' },
] as const;
